blank_issues_enabled: false
contact_links:
  - name: ğŸ§‘â€ğŸ’» Create paircode.dev request.
    url: https://paircode.dev/
    about: Find a developer to get help the issue you issue you're currently facing.
  - name: ğŸ’° Earn money by pair coding.
    url: https://paircode.dev/
    about: paircode.dev is a microfreelancing platform.
    title: test
