blank_issues_enabled: false
contact_links:
  - name: Create paircode.dev request ğŸ§‘â€ğŸ’»
    url: https://paircode.dev/
    about: Find a developer to get help the issue you issue you're currently facing.
  - name: Earn money by pair coding.
    url: https://paircode.dev/as-developer.
    about: paircode.dev is a microfreelancing platform.
    title: test
