blank_issues_enabled: false
contact_links:
  - name: Create paircode.dev request ğŸ§‘â€ğŸ’»
    url: https://paircode.dev/
    about: Find a developer to get help the issue you\' issue you're currently facing.
